/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./constants.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      animation: {
        float: "float 3s ease-in-out infinite",
      },
      borderColor: {
        DEFAULT: "var(--primary-10)",
      },
      borderRadius: {
        DEFAULT: "8px",
      },
      colors: {
        gnd: "var(--gnd)",
        prim: "var(--prim)",
        sec: "var(--sec)",
        ground: "var(--ground)",
        "ground-75": "var(--ground-75)",
        "ground-50": "var(--ground-50)",
        "ground-25": "var(--ground-25)",
        "ground-10": "var(--ground-10)",
        "ground-05": "var(--ground-05)",
        primary: "var(--primary)",
        "primary-75": "var(--primary-75)",
        "primary-50": "var(--primary-50)",
        "primary-25": "var(--primary-25)",
        "primary-10": "var(--primary-10)",
        "primary-05": "var(--primary-05)",
        indigo: "var(--indigo)",
        "indigo-75": "var(--indigo-75)",
        "indigo-50": "var(--indigo-50)",
        "indigo-25": "var(--indigo-25)",
        "indigo-10": "var(--indigo-10)",
        "indigo-05": "var(--indigo-05)",
        green: "var(--green)",
        "green-75": "var(--green-75)",
        "green-50": "var(--green-50)",
        "green-25": "var(--green-25)",
        "green-10": "var(--green-10)",
        "green-05": "var(--green-05)",
        orange: "var(--orange)",
        "orange-75": "var(--orange-75)",
        "orange-50": "var(--orange-50)",
        "orange-25": "var(--orange-25)",
        "orange-10": "var(--orange-10)",
        "orange-05": "var(--orange-05)",
      },
      fontFamily: {
        base: [
          "'ABC DiaType Semi-Mono Variable'",
          "'Maison Neue'",
          "'Gothic A1'",
          "'ABC DiaType Variable'",
          "'Be Vietnam Pro Variable'",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "'Segoe UI'",
          "Roboto",
          "'Helvetica Neue'",
          "Arial",
          "'Noto Sans'",
          "sans-serif",
        ],
        heading: ["'ABC DiaType Variable'", "Editorial New"],
        mono: ["'ABC DiaType Semi-Mono Variable'"],
      },
      keyframes: {
        float: {
          "0%": { transform: "translate(0, -4px)" },
          "50%": { transform: "translate(0, 4px)" },
          "100%": { transform: "translate(0, -4px)" },
        },
      },
      maxWidth: (theme, { breakpoints }) => ({
        ...breakpoints(theme("screens")),
        ...theme("spacing"),
      }),
    },
    // Overrides
    fontSize: {
      "2xl": ["56px", { lineHeight: "1.5" }],
      xl: ["42px", { lineHeight: "1.5" }],
      lg: ["26px", { lineHeight: "34px" }],
      base: ["22px", { lineHeight: "30px" }],
      sm: ["18px", { lineHeight: "26px" }],
      xs: ["16px", { lineHeight: "24px" }],
      "2xs": ["14px", { lineHeight: "20px" }],

      "print-sm": ["8pt", { lineHeight: "12pt" }],
      "print-base": ["10pt", { lineHeight: "14pt" }],
      "print-lg": ["12pt", { lineHeight: "16pt" }],
      "print-xl": ["14pt", { lineHeight: "16pt" }],
    },
    screens: {
      xs: "480px",
      sm: "640px",
      md: "800px",
      lg: "960px",
      xl: "1280px",
      "2xl": "1536px",
      "3xl": "1920px",
    },
    spacing: (theme, { breakpoints }) => ({
      0: "0",
      1: "1px",
      2: "2px",
      4: "4px",
      8: "8px",
      12: "12px",
      16: "16px",
      20: "20px",
      24: "24px",
      28: "28px",
      32: "32px",
      40: "40px",
      48: "48px",
      56: "56px",
      64: "64px",
      72: "72px",
      80: "80px",
      88: "88px",
      96: "96px",
      128: "128px",
      160: "160px",
      192: "192px",
      224: "224px",
      256: "256px",
      288: "288px",
      320: "320px",
      352: "352px",
      384: "384px",
      416: "416px",
      448: "448px",
      480: "480px",
      512: "512px",
      "2em": "2em",
      em: "1em",
      "3/4em": "0.75em",
      "1/2em": "0.5em",
      "1/4em": "0.25em",
      sm: "min(24px, 2vmax)",
      base: "3vmax",
      lg: "6vmax",
      page: "3vmax",
      "page-lg": "max(calc(64px + 3vmax), 3vmax)",
      ...breakpoints(theme("screens")),
    }),
  },
  plugins: [],
};
