/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./constants.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      animation: {
        float: "float 3s ease-in-out infinite",
      },
      borderColor: {
        DEFAULT: "var(--primary-10)",
      },
      borderRadius: {
        DEFAULT: "8px",
      },
      colors: {
        ground: "var(--ground)",
        "ground-75": "var(--ground-75)",
        "ground-50": "var(--ground-50)",
        "ground-25": "var(--ground-25)",
        "ground-10": "var(--ground-10)",
        "ground-05": "var(--ground-05)",
        primary: "var(--primary)",
        "primary-75": "var(--primary-75)",
        "primary-50": "var(--primary-50)",
        "primary-25": "var(--primary-25)",
        "primary-10": "var(--primary-10)",
        "primary-05": "var(--primary-05)",
        secondary: "var(--secondary)",
        "secondary-75": "var(--secondary-75)",
        "secondary-50": "var(--secondary-50)",
        "secondary-25": "var(--secondary-25)",
        "secondary-10": "var(--secondary-10)",
        "secondary-05": "var(--secondary-05)",
        highlight: "var(--highlight)",
        "highlight-75": "var(--highlight-75)",
        "highlight-50": "var(--highlight-50)",
        "highlight-25": "var(--highlight-25)",
        "highlight-10": "var(--highlight-10)",
        "highlight-05": "var(--highlight-05)",
      },
      fontFamily: {
        sans: [
          "Output Sans",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        serif: [
          "Tiempos Headline",
          "ui-serif",
          "Georgia",
          "Cambria",
          '"Times New Roman"',
          "Times",
          "serif",
        ],
      },
      keyframes: {
        float: {
          "0%": { transform: "translate(0, -4px)" },
          "50%": { transform: "translate(0, 4px)" },
          "100%": { transform: "translate(0, -4px)" },
        },
      },
      maxWidth: (theme, { breakpoints }) => ({
        ...breakpoints(theme("screens")),
        ...theme("spacing"),
      }),
      minHeight: (theme, { breakpoints }) => ({
        ...breakpoints(theme("screens")),
        ...theme("spacing"),
      }),
    },
    // Overrides
    fontSize: {
      "2xl": ["64px", { lineHeight: "1.15" }],
      xl: ["42px", { lineHeight: "1.15" }],
      lg: ["26px", { lineHeight: "34px" }],
      base: ["22px", { lineHeight: "30px" }],
      sm: ["18px", { lineHeight: "26px" }],
      xs: ["16px", { lineHeight: "24px" }],
      "2xs": ["14px", { lineHeight: "20px" }],

      "print-sm": ["8pt", { lineHeight: "12pt" }],
      "print-base": ["10pt", { lineHeight: "14pt" }],
      "print-lg": ["12pt", { lineHeight: "16pt" }],
      "print-xl": ["14pt", { lineHeight: "16pt" }],
    },
    screens: {
      xs: "480px",
      sm: "640px",
      md: "800px",
      lg: "960px",
      xl: "1280px",
      "2xl": "1536px",
      "3xl": "1920px",
    },
    spacing: (theme, { breakpoints }) => ({
      0: "0",
      1: "1px",
      2: "2px",
      4: "4px",
      8: "8px",
      12: "12px",
      16: "16px",
      20: "20px",
      24: "24px",
      28: "28px",
      32: "32px",
      40: "40px",
      48: "48px",
      56: "56px",
      64: "64px",
      72: "72px",
      80: "80px",
      88: "88px",
      96: "96px",
      128: "128px",
      160: "160px",
      192: "192px",
      224: "224px",
      256: "256px",
      288: "288px",
      320: "320px",
      352: "352px",
      384: "384px",
      416: "416px",
      448: "448px",
      480: "480px",
      512: "512px",
      "2em": "2em",
      em: "1em",
      "3/4em": "0.75em",
      "1/2em": "0.5em",
      "1/4em": "0.25em",
      sm: "min(24px, 2vmax)",
      base: "3vmax",
      lg: "6vmax",
      ...breakpoints(theme("screens")),
    }),
  },
  plugins: [],
};
